### ISSUE TITLE
Milestone 1 Preliminary Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/522-Workflows-Group-414#18]
- Very good and detailed proposal.
- You do mention it in the proposal, but choose the specific models and evaluation metrics you will use to compare them.

**Comment by tejasph** [comment]
Thanks for the feedback!

**Comment by matthewconnell** [comment]
Fixed with commit: https://github.com/UBC-MDS/522-Workflows-Group-414/commit/65af895c11c7c0b500fb6ba71aff284c25c904e7
