### ISSUE TITLE
Milestone 2 Feedback: Mechanics

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/522-Workflows-Group-414#54]
- [x] You need tests for each function in the analysis

- [x] You can update your README in a way that the README is the landing page of your project, i.e. an introduction to your project. So you can get rid of the "proposal" language and also remove detailed information about the analysis since these are already included in the report. You should just have a link to the report on the README.

**Comment by MrThomasPin** [comment]
Updated readme to clean it up
