### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/522-Workflows-Group-414#67]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] THANK YOU (!!) for having a table at the beginning that has a human-readable version of the column/feature names
- - [x] Great job adding figure numbers and captions!
- - [x] Figure 1: 
	- - [x] This is great! Excellent work on this confusion matrix, and kudos for rounding your values to 3 digits - most people don't do this but doing it really improves readability. If it was me, I'd go to 2 sig figs but it's up to you
- - [x] Figure 2:
	- - [x] This is great, good call on removing the diagonal elements, they're pretty distracting at the max value
	- - [x] I'd suggest removing gridlines and the frame so it's just a heatmap
	- - [x] Ideally, you only want to show half the correlation map as the other half is redundant (see example [here](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-correlation-matrix-heatmap-add-correlation-coefficients-1.png))
- - [x] Figure 3:
	- - [x] This is a great use of a stacked bar chart! Nice.
- - [x] Overall the report looks very polished and clean! Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by tejasph** [comment]
Awesome feedback Firas! We have implemented changes based on your observations.

**Comment by matthewconnell** [comment]
Addressed with cec426cd128f884e18501779353e0feb5dbe037a
